events {}

http {
    resolver 127.0.0.11 valid=10s;

    server {
        listen 80;

        location /auth/ {
            set $upstream http://authorization-service:3001;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/blogs {
            set $upstream http://blogs-service:8082;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/tours {
            set $upstream http://tours-service:8083;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /follows {
            set $upstream http://follower-service:8000;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /me {
            set $upstream http://follower-service:8000;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
