// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: tours.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishTourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourId        string `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Authorization string `protobuf:"bytes,2,opt,name=authorization,proto3" json:"authorization,omitempty"`
}

func (x *PublishTourRequest) Reset() {
	*x = PublishTourRequest{}
	mi := &file_tours_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTourRequest) ProtoMessage() {}

func (x *PublishTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTourRequest.ProtoReflect.Descriptor instead.
func (*PublishTourRequest) Descriptor() ([]byte, []int) {
	return file_tours_proto_rawDescGZIP(), []int{0}
}

func (x *PublishTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *PublishTourRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

type ListPublishedToursRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
}

func (x *ListPublishedToursRequest) Reset() {
	*x = ListPublishedToursRequest{}
	mi := &file_tours_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishedToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishedToursRequest) ProtoMessage() {}

func (x *ListPublishedToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishedToursRequest.ProtoReflect.Descriptor instead.
func (*ListPublishedToursRequest) Descriptor() ([]byte, []int) {
	return file_tours_proto_rawDescGZIP(), []int{1}
}

func (x *ListPublishedToursRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

type TourResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourJson string `protobuf:"bytes,1,opt,name=tour_json,json=tourJson,proto3" json:"tour_json,omitempty"`
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_tours_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_tours_proto_rawDescGZIP(), []int{2}
}

func (x *TourResponse) GetTourJson() string {
	if x != nil {
		return x.TourJson
	}
	return ""
}

type PublishedToursResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToursJson string `protobuf:"bytes,1,opt,name=tours_json,json=toursJson,proto3" json:"tours_json,omitempty"`
}

func (x *PublishedToursResponse) Reset() {
	*x = PublishedToursResponse{}
	mi := &file_tours_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedToursResponse) ProtoMessage() {}

func (x *PublishedToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedToursResponse.ProtoReflect.Descriptor instead.
func (*PublishedToursResponse) Descriptor() ([]byte, []int) {
	return file_tours_proto_rawDescGZIP(), []int{3}
}

func (x *PublishedToursResponse) GetToursJson() string {
	if x != nil {
		return x.ToursJson
	}
	return ""
}

var File_tours_proto protoreflect.FileDescriptor

var file_tours_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x6f, 0x75, 0x72, 0x73, 0x22, 0x53, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54,
	0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f,
	0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x75,
	0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x41, 0x0a, 0x19, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x0c,
	0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x6f, 0x75, 0x72, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x6f, 0x75, 0x72, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x16, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x5f, 0x6a, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x4a, 0x73,
	0x6f, 0x6e, 0x32, 0xa4, 0x01, 0x0a, 0x0c, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x6f,
	0x75, 0x72, 0x12, 0x19, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x74, 0x6f, 0x75, 0x72, 0x73, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x55, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x54, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x20, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x73,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x54, 0x6f,
	0x75, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x6f, 0x75,
	0x72, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x54, 0x6f, 0x75, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tours_proto_rawDescOnce sync.Once
	file_tours_proto_rawDescData = file_tours_proto_rawDesc
)

func file_tours_proto_rawDescGZIP() []byte {
	file_tours_proto_rawDescOnce.Do(func() {
		file_tours_proto_rawDescData = protoimpl.X.CompressGZIP(file_tours_proto_rawDescData)
	})
	return file_tours_proto_rawDescData
}

var file_tours_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tours_proto_goTypes = []any{
	(*PublishTourRequest)(nil),        // 0: tours.PublishTourRequest
	(*ListPublishedToursRequest)(nil), // 1: tours.ListPublishedToursRequest
	(*TourResponse)(nil),              // 2: tours.TourResponse
	(*PublishedToursResponse)(nil),    // 3: tours.PublishedToursResponse
}
var file_tours_proto_depIdxs = []int32{
	0, // 0: tours.ToursService.PublishTour:input_type -> tours.PublishTourRequest
	1, // 1: tours.ToursService.ListPublishedTours:input_type -> tours.ListPublishedToursRequest
	2, // 2: tours.ToursService.PublishTour:output_type -> tours.TourResponse
	3, // 3: tours.ToursService.ListPublishedTours:output_type -> tours.PublishedToursResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tours_proto_init() }
func file_tours_proto_init() {
	if File_tours_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tours_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tours_proto_goTypes,
		DependencyIndexes: file_tours_proto_depIdxs,
		MessageInfos:      file_tours_proto_msgTypes,
	}.Build()
	File_tours_proto = out.File
	file_tours_proto_rawDesc = nil
	file_tours_proto_goTypes = nil
	file_tours_proto_depIdxs = nil
}
